<a href="https://colab.research.google.com/github/Hsuan7/-/blob/main/%E9%87%91%E8%9E%8D%E5%A4%A7%E6%95%B8%E6%93%9Aw2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 發送 HTTP 請求以獲取網路上的資料
import requests

# 用來處理和分析結構化數據
import pandas as pd

# 用來處理時間
import datetime as dt

In [ ]:
# "聯華電子"股票代號
stock_id = '2330'

# 獲取今天的日期（型別：str）
date = dt.date.today().strftime("%Y%m%d")
# date = 20241101

print('今日日期：', date)

# 取得證交所網站資料，帶入網址參數 date：時間，stock_id：股票代號
# https://www.twse.com.tw/rwd/zh/afterTrading/STOCK_DAY?date=20240918&stockNo=2303
stock_data = requests.get(f'https://www.twse.com.tw/rwd/zh/ \
            afterTrading/STOCK_DAY?date={date}&stockNo={stock_id}')

# 將結果轉換 JSON 格式
json_data = stock_data.json()

# 將 JSON 格式轉換爲 Dataframe 格式，
# 方便在 Python 中處理結構化資料
df = pd.DataFrame(data=json_data['data'],
                  columns=json_data['fields'])

df

今日日期： 20240919

,日期,成交股數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,成交筆數
0,113/09/02,"19,272,593","18,270,058,260",950.00,955.00,943.00,948.00,+4.00,"31,642"
1,113/09/03,"23,205,623","21,908,471,541",948.00,952.00,939.00,940.00,-8.00,"47,139"
2,113/09/04,"93,169,835","83,424,133,824",894.00,905.00,888.00,889.00,-51.00,"393,210"
3,113/09/05,"34,147,890","30,998,595,394",907.00,915.00,900.00,902.00,+13.00,"63,902"
4,113/09/06,"28,248,063","25,786,016,936",909.00,918.00,903.00,918.00,+16.00,"38,415"
5,113/09/09,"38,448,946","34,456,838,126",892.00,900.00,891.00,899.00,-19.00,"102,365"
6,113/09/10,"34,312,646","31,067,424,234",907.00,911.00,901.00,904.00,+5.00,"45,141"
7,113/09/11,"19,513,256","17,621,000,956",906.00,906.00,900.00,901.00,-3.00,"30,789"
8,113/09/12,"43,749,260","40,999,951,508",936.00,944.00,928.00,940.00,X0.00,"80,643"
9,113/09/13,"28,307,441","26,795,862,243",955.00,955.00,939.00,947.00,+7.00,"39,071"
10,113/09/16,"14,456,888","13,692,259,575",952.00,952.00,943.00,947.00,0.00,"26,421"
11,113/09/18,"30,094,662","28,303,054,525",945.00,948.00,933.00,941.00,-6.00,"46,622"
12,113/09/19,"32,610,000","30,965,604,000",940.00,960.00,936.00,960.00,+19.00,"16,167"

In [ ]:
# 設定查找時間
date_list = ['20240701', '20240801', '20240901']

all_df = pd.DataFrame()

# 使用迴圈抓取連續月份資料
for date in date_list:
    # 取得證交所網站資料，帶入網址參數 date：時間，stock_id：股票代號
    # https://www.twse.com.tw/rwd/zh/afterTrading/STOCK_DAY?date=20240918&stockNo=2303
    # https://www.twse.com.tw/rwd/zh/afterTrading/BWIBBU?date=20240303&stockNo=2303
    url = f'https://www.twse.com.tw/rwd/zh/afterTrading/\
      BWIBBU?date={date}&stockNo={stock_id}'

    try:

        # 取得證交所網站資
        stock_data = requests.get(url)

        # 將結果轉換 JSON 格式
        json_data = stock_data.json()

        # 將 JSON 格式轉換爲 Dataframe 格式，
        # 方便在 Python 中處理結構化資料
        df = pd.DataFrame(data=json_data['data'],
                          columns=json_data['fields'])

        # 添加新數據
        all_df = pd.concat([all_df, df], ignore_index=True)

    except Exception as e:

        # 發生錯誤時，列印錯誤訊息
        print(f'無法取得{date}的資料, 可能資料量不足.')


# 輸出前 5 筆資料
print(all_df)

            日期 殖利率(%)  股利年度    本益比 股價淨值比  財報年/季
0   113年07月01日   1.34   112  29.30  6.90  113/1
1   113年07月02日   1.35   112  29.06  6.85  113/1
2   113年07月03日   1.33   112  29.63  6.98  113/1
3   113年07月04日   1.29   112  30.42  7.17  113/1
4   113年07月05日   1.29   112  30.42  7.17  113/1
5   113年07月08日   1.26   112  31.33  7.38  113/1
6   113年07月09日   1.25   112  31.48  7.42  113/1
7   113年07月10日   1.24   112  31.63  7.45  113/1
8   113年07月11日   1.20   112  32.69  7.70  113/1
9   113年07月12日   1.25   112  31.48  7.42  113/1
10  113年07月15日   1.25   112  31.48  7.42  113/1
11  113年07月16日   1.23   112  31.93  7.53  113/1
12  113年07月17日   1.26   112  31.17  7.35  113/1
13  113年07月18日   1.29   112  30.42  7.17  113/1
14  113年07月19日   1.34   112  29.36  6.92  113/1
15  113年07月22日   1.38   112  28.42  6.70  113/1
16  113年07月23日   1.33   112  29.63  6.98  113/1
17  113年07月26日   1.41   112  27.97  6.59  113/1
18  113年07月29日   1.38   112  28.57  6.73  113/1
19  113年07月30日   1.38   112  28.45  6.71  113/1
20  113年07月31日   1.39   112  28.27  6.66  113/1
21  113年08月01日   1.35   112  29.06  6.85  113/1
22  113年08月02日   1.44   112  27.33  6.44  113/1
23  113年08月05日   1.60   112  24.67  5.81  113/1
24  113年08月06日   1.48   112  26.63  6.28  113/1
25  113年08月07日   1.41   112  27.85  6.56  113/1
26  113年08月08日   1.45   112  27.12  6.39  113/1
27  113年08月09日   1.39   112  28.27  6.66  113/1
28  113年08月12日   1.38   112  28.45  6.71  113/1
29  113年08月13日   1.38   112  28.48  6.71  113/1
30  113年08月14日   1.37   112  26.63  6.48  113/2
31  113年08月15日   1.38   112  26.49  6.45  113/2
32  113年08月16日   1.34   112  27.22  6.63  113/2
33  113年08月19日   1.34   112  27.33  6.65  113/2
34  113年08月20日   1.34   112  27.33  6.65  113/2
35  113年08月21日   1.36   112  26.91  6.55  113/2
36  113年08月22日   1.37   112  26.71  6.50  113/2
37  113年08月23日   1.37   112  26.66  6.49  113/2
38  113年08月26日   1.37   112  26.69  6.50  113/2
39  113年08月27日   1.38   112  26.46  6.44  113/2
40  113年08月28日   1.35   112  27.08  6.59  113/2
41  113年08月29日   1.38   112  26.49  6.45  113/2
42  113年08月30日   1.38   112  26.52  6.46  113/2
43  113年09月02日   1.37   112  26.63  6.48  113/2
44  113年09月03日   1.38   112  26.40  6.43  113/2
45  113年09月04日   1.46   112  24.97  6.08  113/2
46  113年09月05日   1.44   112  25.34  6.17  113/2
47  113年09月06日   1.42   112  25.79  6.28  113/2
48  113年09月09日   1.45   112  25.25  6.15  113/2
49  113年09月10日   1.44   112  25.39  6.18  113/2
50  113年09月11日   1.44   112  25.31  6.16  113/2
51  113年09月12日   1.38   112  26.40  6.43  113/2
52  113年09月13日   1.37   112  26.60  6.48  113/2
53  113年09月16日   1.37   112  26.60  6.48  113/2
54  113年09月18日   1.38   112  26.43  6.44  113/2

In [ ]:
# 用來處理時間
from datetime import datetime
# 解析網頁內容
from bs4 import BeautifulSoup

In [ ]:
def yahoo_stock(stock_id):
    # 取得證交所網站資，帶入網址參數 date：時間，stock_id：股票代號
    url = f'https://tw.stock.yahoo.com/quote/{stock_id}.TW'

    # 使用 requests 取得網頁內容
    response = requests.get(url)

    # 取得 HTML 文本
    html = response.content

    # 使用 Beautiful Soup 解析 HTML 內容
    soup = BeautifulSoup(html, 'html.parser')

    # 使用 find 與 find_all 定位 HTML 的標籤
    # HTML 標籤中的 section id=qsp-overview-realtime-info 下的 time
    time_element = soup.find('section',\
                {'id': 'qsp-overview-realtime-info'}).find('time')
    # HTML 標籤中的 section id=qsp-overview-realtime-info 下的 ul li
    table_soups = soup.find('section',\
                {'id': 'qsp-overview-realtime-info'}).find('ul')\
                                   .find_all('li')

    # 欄位資料
    fields = []
    # 放資料
    datas = []

    # 使用 for 迴圈取得表格中細部內容
    for table_soup in table_soups:

        # 表格中的 span 標籤
        table_datas = table_soup.find_all('span')

        for num, table_data in enumerate(table_datas):

            if table_data.text == '': # 表格內容空就跳過
                continue

            # 新增資料
            if num == 0:
                fields.append(table_data.text)
            else:
                datas.append(table_data.text)

    # 建立 DataFrame
    df = pd.DataFrame([datas], columns=fields)

    # 增加日期和股號欄位
    df.insert(0,'日期',time_element['datatime'])
    df.insert(1,'股號',stock_id)

    # 回傳 DataFrame
    return df


'''main'''

# "聯華電子"股票代號
stock_id = '2330'

# 呼叫定義函數
yahoo_stock(stock_id)

,日期,股號,成交,開盤,最高,最低,均價,成交金額(億),昨收,漲跌幅,漲跌,總量,昨量,振幅
0,2024/09/19 13:30,2330,960,940,960,936,949,309.66,941,2.02%,19.00,"32,610","28,394",2.55%

In [ ]:
url = f'https://tw.stock.yahoo.com/quote/{stock_id}/income-statement'
words = url.split('/')
print(words)

k = words[-1]
print(k)

['https:', '', 'tw.stock.yahoo.com', 'quote', '2330', 'income-statement']
income-statement

In [ ]:
# 函數可用於奇摩財報
def url_find(url):

    # 取得 url 的所有 route
    words = url.split('/')

    # 取得最後一個 route
    # 為了知道是損益表、資產負債表、現金流量表
    laset_word = words[-1]

    # 使用requests取得網頁內容
    response = requests.get(url)

    # 取得 HTML 文本
    html = response.content

    # 使用Beautiful Soup解析HTML內容
    soup = BeautifulSoup(html, 'html.parser')

    # 找到表格的表頭 qsp-incom-statment-table
    table_soup = soup.find('section', {'id': 'qsp-{}-table'.format(laset_word)})

    # 找到對應類別標籤
    table_fields=table_soup.find('div', class_='table-header')

    # 解析表頭內容
    table_fields_lines = list(table_fields.stripped_strings)


    # 找到對應的資料
    data_rows = table_soup.find_all('li' ,class_='List(n)')

    # 解析資料行內容
    data = []
    for row in data_rows:
        row_data = list(row.stripped_strings)
        data.append(row_data)

    # 建立 DataFrame
    df = pd.DataFrame(data, columns=table_fields_lines)
    return df

'''main'''

# 抓損益表
# url = f'https://tw.stock.yahoo.com/quote/{stock_id}/income-statement'
# 抓資產負債表
# url = f'https://tw.stock.yahoo.com/quote/{stock_id}/balance-sheet'
# 抓現金流量表
url = f'https://tw.stock.yahoo.com/quote/{stock_id}/cash-flow-statement'

# 抓取季報表資料
df = url_find(url).transpose()

# 資料處理
df.columns = df.iloc[0]
df = df[1:]
df.insert(0, '年度/季別', df.index)
df.columns.name = None
df.reset_index(drop=True, inplace=True)

# 輸出資料後5筆
print(df)

      年度/季別        營業現金流         投資現金流         融資現金流        自由現金流  \
0   2024 Q2  377,668,210  -197,607,330   -90,244,583  180,060,880
1   2024 Q1  436,311,108  -159,806,991   -71,685,617  276,504,117
2   2023 Q4  394,829,347  -132,319,502   -75,367,133  262,509,845
3   2023 Q3  294,645,276  -242,243,223   -38,451,204   52,402,053
4   2023 Q2  167,247,979  -259,326,076   -26,588,885  -92,078,097
5   2023 Q1  385,244,745  -272,231,795   -64,487,030  113,012,950
6   2022 Q4  486,881,904  -342,532,013   -69,831,545  144,349,891
7   2022 Q3  412,698,167  -284,390,325  -130,406,753  128,307,842
8   2022 Q2  338,849,429  -275,932,106    19,080,454   62,917,323
9   2022 Q1  372,169,688  -288,073,791   -19,086,188   84,095,897
10  2021 Q4  378,199,317  -245,343,292    82,284,018  132,856,025
11  2021 Q3  318,706,207  -177,020,159   -35,324,719  141,686,048
12  2021 Q2  187,439,492  -169,750,998    75,030,682   17,688,494
13  2021 Q1  227,815,706  -244,251,414    14,618,457  -16,435,708
14  2020 Q4  259,130,584   -90,958,613  -101,203,795  168,171,971
15  2020 Q3  190,171,227   -96,079,669    47,434,066   94,091,558
16  2020 Q2  170,334,959  -129,750,164     5,912,053   40,584,795
17  2020 Q1  203,029,442  -188,993,268   -40,757,411   14,036,174
18  2019 Q4  202,954,417  -171,605,106   -17,182,776   31,349,311
19  2019 Q3  141,753,021  -108,290,117  -229,112,243   33,462,904

            淨現金流
0    100,931,647
1    232,767,951
2    153,621,218
3     35,082,551
4   -108,508,826
5     42,418,727
6     46,801,299
7     42,823,587
8    101,599,551
9     86,599,454
10   211,178,226
11   105,829,884
12    83,254,225
13     4,557,210
14    55,975,534
15   136,581,670
16    36,836,214
17   -24,622,107
18     2,969,036
19  -197,266,962